[DEFAULT]
# Acceptable values are sandbox or production
environment = SANDBOX

[PRODUCTION]
square_application_id = production_application_id
square_access_token = production_access_token
square_location_id = production_location_id

[SANDBOX]
square_application_id = sandbox-sq0idb-EatW_1CuQHzCGlGDkkxJhw
square_access_token = EAAAl_0QhSnq0KtkiiftPFciQnKzncpiOrxnvLC-cYWs7gAkHmlWUvrwh6Y7gNgy
square_location_id = L0VNGH5V47Y5Q