version: "3.7"

services:
  website:
    image: techtonica/website
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: main_site.py
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app:cached
    ports:
      - ${SERVER_PORT:-5000}:${SERVER_PORT:-5000}
