version: "3"

services:
  website:
    build:
      context: .
    image: techtonica/website
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: main_site.py
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
